sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: xHRAyNDidoOmKmEDDb1hKIkfv5zhMFlwPmT9+4M2MdERsP8v782p4zg882yla9LcG1PtyYMS9CgikkOe6r4xWZZgxAKVsov0PxYVBauL+kUb8zUUlxE3zXhBWmw3P1TSyBvEzvzcCtKfncQrWG+pEQ1D3tDPd0OTDxlIQuhPjtfE4lOHtPFkEBIVjH4hTG5ckW73Woffqyo4SlYzcEQw9XNLZlqUGqmSreVVBycKrA4tLW8NnV9xKVGhPKjXj3INAkVUDQGL/MKQOP+yzWxg/XJr+K3jqqWshFxnECEcCX4eK9SGCAm/pmqGr98ESWZoej1d2Poa8FKkt1m1woYsj0loMTXQQ+YkZg7v9bG0ftu0ipn7nqEYftx3iBIqntF04Al3Dw2gZ0z6QJvUEceFu4iQqWZdR/oxqfgO8YGBZXwfYkvaNG8pHj9A4sK1gDuXAv1EU2/Tg5d0We1lFK3ZqsO51i6t9ZuE/DSYHWYSA/SV090FqWXBkXuxvNxZSYG+dO9rYvBb8dQYz+liOtooSAPvg++mICPKCw42jDnuPy1o9s+TEyB+tLmUmsik7Eil3LxrEfyP8ZQy8Z+HQBKp6Ig62nLMZbEGzzyKzYQc0srQinKoibtb5CxG1kLZCEMwCMDO0bkDIxYp/Js74e/bbjhZITebzOXxfUtg0wQPa1o=
  on: heroku_production
  app: probot-stnws

